#!/usr/bin/env python3
"""
ImmPort parsed-data adapter for Hypothesis2Omics.

This adapter uses:
1. the normalized sample_manifest.tsv generated by the team's
   immport_parse_module.py; and
2. the original ImmPort *_Tab.zip archive.

It converts real participant/sample-level ImmPort data into the evidence
format consumed by eligibility_engine.py.

For the YF-17D / GCN2 / CD8 proof-of-concept, it verifies:
- human study
- YF-17D vaccination context
- transcriptomic predictor data
- quantitative CD8 response values
- early predictor / later outcome timepoints
- participant-level predictor/outcome linkage
- predictor and outcome accessibility

EIF2AK4/GCN2 feature measurability is intentionally left unresolved until
the GEO expression platform/matrix is inspected directly.
"""

from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd


def evidence_item(
    value: str,
    confidence: str,
    evidence: str,
    sources: List[str],
) -> Dict[str, Any]:

    return {
        "value": value,
        "confidence": confidence,
        "evidence": evidence,
        "sources": sources,
    }


def read_zip_table(
    zip_path: Path,
    basename: str,
) -> pd.DataFrame:

    with zipfile.ZipFile(zip_path) as archive:

        matches = [
            name
            for name in archive.namelist()
            if name.lower().endswith(
                "/" + basename.lower()
            )
            or name.lower() == basename.lower()
        ]

        if not matches:
            raise FileNotFoundError(
                f"{basename} not found in {zip_path}"
            )

        with archive.open(matches[0]) as handle:
            return (
                pd.read_csv(
                    handle,
                    sep="\t",
                    dtype=str,
                )
                .fillna("")
            )


def numeric_series(
    series: pd.Series,
) -> pd.Series:

    return pd.to_numeric(
        series,
        errors="coerce",
    )


def infer_study_accession(
    manifest: pd.DataFrame,
) -> str:

    values = [
        value
        for value in manifest[
            "study_accession"
        ].astype(str).unique()
        if value
    ]

    if not values:
        return "IMM_UNKNOWN"

    return values[0].upper()


def contains_terms(
    series: pd.Series,
    terms: List[str],
) -> pd.Series:

    text = series.astype(str).str.lower()

    mask = pd.Series(
        False,
        index=series.index,
    )

    for term in terms:
        mask = mask | text.str.contains(
            term.lower(),
            regex=False,
            na=False,
        )

    return mask


def build_evidence(
    manifest_path: Path,
    tab_zip_path: Path,
) -> Dict[str, Any]:

    manifest = (
        pd.read_csv(
            manifest_path,
            sep="\t",
            dtype=str,
        )
        .fillna("")
    )

    required_manifest_columns = {
        "study_accession",
        "experiment_name",
        "measurement_technique",
        "repository_name",
        "repository_accession",
        "subject_accession",
        "study_time_collected",
        "study_time_collected_unit",
        "biosample_type",
        "species",
    }

    missing = (
        required_manifest_columns
        - set(manifest.columns)
    )

    if missing:
        raise ValueError(
            "sample_manifest.tsv is missing required columns: "
            + ", ".join(sorted(missing))
        )

    accession = infer_study_accession(
        manifest
    )

    source_manifest = (
        f"ImmPort:{accession}:sample_manifest.tsv"
    )

    source_lab_test = (
        f"ImmPort:{accession}:lab_test.txt"
    )

    source_biosample = (
        f"ImmPort:{accession}:biosample.txt"
    )

    # ----------------------------------------------------------
    # Human study
    # ----------------------------------------------------------

    human_mask = contains_terms(
        manifest["species"],
        [
            "homo sapiens",
            "human",
        ],
    )

    human_count = int(
        human_mask.sum()
    )

    human_true = human_count > 0

    # ----------------------------------------------------------
    # YF-17D study context
    # ----------------------------------------------------------

    searchable_columns = [
        "experiment_name",
        "arm_name",
        "arm_type_reported",
        "arm_type_preferred",
    ]

    available_search_columns = [
        column
        for column in searchable_columns
        if column in manifest.columns
    ]

    study_text = (
        manifest[
            available_search_columns
        ]
        .astype(str)
        .agg(" ".join, axis=1)
    )

    yf17d_mask = contains_terms(
        study_text,
        [
            "yf17d",
            "yf-17d",
            "yellow fever",
        ],
    )

    yf17d_true = bool(
        yf17d_mask.any()
    )

    # ----------------------------------------------------------
    # Transcriptomics
    # ----------------------------------------------------------

    transcriptomic_mask = contains_terms(
        manifest[
            "measurement_technique"
        ],
        [
            "transcription",
            "transcript",
            "microarray",
            "rna-seq",
            "rna seq",
            "gene expression",
        ],
    )

    transcriptomics = manifest[
        transcriptomic_mask
    ].copy()

    transcriptomics_true = (
        len(transcriptomics) > 0
    )

    tx_days = numeric_series(
        transcriptomics[
            "study_time_collected"
        ]
    )

    transcriptomics[
        "_study_day"
    ] = tx_days

    early_tx = transcriptomics[
        transcriptomics[
            "_study_day"
        ].between(
            0,
            7,
            inclusive="both",
        )
    ].copy()

    early_tx_subjects = {
        value
        for value in early_tx[
            "subject_accession"
        ].astype(str)
        if value
    }

    geo_accessions = sorted(
        {
            value
            for value in transcriptomics[
                "repository_accession"
            ].astype(str)
            if value.upper().startswith("GSM")
        }
    )

    predictor_accessible = (
        transcriptomics_true
        and len(geo_accessions) > 0
    )

    # ----------------------------------------------------------
    # Raw ImmPort lab-test data
    # ----------------------------------------------------------

    lab_test = read_zip_table(
        tab_zip_path,
        "lab_test.txt",
    )

    biosample = read_zip_table(
        tab_zip_path,
        "biosample.txt",
    )

    required_lab_columns = {
        "LAB_TEST_ACCESSION",
        "LAB_TEST_PANEL_ACCESSION",
        "BIOSAMPLE_ACCESSION",
        "NAME_PREFERRED",
        "NAME_REPORTED",
        "RESULT_UNIT_PREFERRED",
        "RESULT_UNIT_REPORTED",
        "RESULT_VALUE_PREFERRED",
        "RESULT_VALUE_REPORTED",
    }

    missing_lab = (
        required_lab_columns
        - set(lab_test.columns)
    )

    if missing_lab:
        raise ValueError(
            "lab_test.txt is missing required columns: "
            + ", ".join(sorted(missing_lab))
        )

    required_biosample_columns = {
        "BIOSAMPLE_ACCESSION",
        "SUBJECT_ACCESSION",
        "STUDY_TIME_COLLECTED",
        "STUDY_TIME_COLLECTED_UNIT",
    }

    missing_biosample = (
        required_biosample_columns
        - set(biosample.columns)
    )

    if missing_biosample:
        raise ValueError(
            "biosample.txt is missing required columns: "
            + ", ".join(
                sorted(missing_biosample)
            )
        )

    # ----------------------------------------------------------
    # Quantitative CD8 outcome
    # ----------------------------------------------------------

    name_text = (
        lab_test[
            "NAME_PREFERRED"
        ].astype(str)
        + " "
        + lab_test[
            "NAME_REPORTED"
        ].astype(str)
    )

    cd8_mask = contains_terms(
        name_text,
        [
            "cd8",
            "cd8+",
            "cd8 t cell",
        ],
    )

    cd8 = lab_test[
        cd8_mask
    ].copy()

    preferred_numeric = numeric_series(
        cd8[
            "RESULT_VALUE_PREFERRED"
        ]
    )

    reported_numeric = numeric_series(
        cd8[
            "RESULT_VALUE_REPORTED"
        ]
    )

    cd8[
        "_numeric_value"
    ] = preferred_numeric.fillna(
        reported_numeric
    )

    cd8_quantitative = cd8[
        cd8["_numeric_value"].notna()
    ].copy()

    cd8_quantitative_true = (
        len(cd8_quantitative) > 0
    )

    # ----------------------------------------------------------
    # Link CD8 result -> biosample -> subject/timepoint
    # ----------------------------------------------------------

    cd8_linked = cd8_quantitative.merge(
        biosample[
            [
                "BIOSAMPLE_ACCESSION",
                "SUBJECT_ACCESSION",
                "STUDY_TIME_COLLECTED",
                "STUDY_TIME_COLLECTED_UNIT",
            ]
        ],
        on="BIOSAMPLE_ACCESSION",
        how="left",
    )

    cd8_linked[
        "_outcome_day"
    ] = numeric_series(
        cd8_linked[
            "STUDY_TIME_COLLECTED"
        ]
    )

    cd8_linked_subjects = {
        value
        for value in cd8_linked[
            "SUBJECT_ACCESSION"
        ].astype(str)
        if value
    }

    n_cd8_rows = len(
        cd8_quantitative
    )

    n_cd8_subjects = len(
        cd8_linked_subjects
    )

    n_cd8_with_subject = int(
        cd8_linked[
            "SUBJECT_ACCESSION"
        ]
        .astype(str)
        .ne("")
        .sum()
    )

    complete_cd8_subject_mapping = (
        n_cd8_rows > 0
        and n_cd8_with_subject
        == n_cd8_rows
    )

    outcome_days = sorted(
        {
            int(value)
            for value in cd8_linked[
                "_outcome_day"
            ].dropna()
        }
    )

    # ----------------------------------------------------------
    # Participant-level predictor/outcome overlap
    # ----------------------------------------------------------

    overlap_subjects = sorted(
        early_tx_subjects
        & cd8_linked_subjects
    )

    all_cd8_have_early_tx = (
        len(cd8_linked_subjects) > 0
        and cd8_linked_subjects.issubset(
            early_tx_subjects
        )
    )

    participant_linkage_true = (
        complete_cd8_subject_mapping
        and all_cd8_have_early_tx
    )

    # ----------------------------------------------------------
    # Appropriate predictor/outcome timing
    # ----------------------------------------------------------

    early_days = sorted(
        {
            int(value)
            for value in early_tx[
                "_study_day"
            ].dropna()
        }
    )

    later_cd8_exists = any(
        day > 7
        for day in outcome_days
    )

    appropriate_timepoints_true = (
        participant_linkage_true
        and bool(early_days)
        and later_cd8_exists
    )

    # ----------------------------------------------------------
    # Outcome accessibility
    # ----------------------------------------------------------

    outcome_accessible_true = (
        cd8_quantitative_true
        and complete_cd8_subject_mapping
    )

    # ----------------------------------------------------------
    # EIF2AK4 / GCN2
    #
    # Do NOT infer gene-level feature coverage merely from the
    # existence of a transcriptomic assay.
    # ----------------------------------------------------------

    eif_value = "unknown"
    eif_confidence = "medium"

    eif_evidence = (
        "Transcriptomic predictor data are available and linked to GEO, "
        "but EIF2AK4/GCN2 feature coverage has not yet been verified "
        "directly from the GEO platform or expression matrix."
    )

    # ----------------------------------------------------------
    # Timepoints across both data sources
    # ----------------------------------------------------------

    all_manifest_days = numeric_series(
        manifest[
            "study_time_collected"
        ]
    )

    all_timepoints = sorted(
        {
            int(value)
            for value in all_manifest_days.dropna()
        }
        | set(outcome_days)
    )

    # ----------------------------------------------------------
    # Build evidence
    # ----------------------------------------------------------

    criteria = {

        "human_study": evidence_item(
            "true"
            if human_true
            else "unknown",
            "high"
            if human_true
            else "low",
            (
                f"{human_count} parsed ImmPort experimental-sample rows "
                "are annotated as Homo sapiens."
                if human_true
                else
                "Human study status was not established."
            ),
            [
                source_manifest,
            ],
        ),

        "yf17d_vaccination": evidence_item(
            "true"
            if yf17d_true
            else "unknown",
            "high"
            if yf17d_true
            else "low",
            (
                "YF17D/yellow-fever terminology is present in the "
                "ImmPort experiment metadata."
                if yf17d_true
                else
                "YF-17D vaccination context was not established."
            ),
            [
                source_manifest,
            ],
        ),

        "transcriptomics_available": evidence_item(
            "true"
            if transcriptomics_true
            else "unknown",
            "high"
            if transcriptomics_true
            else "low",
            (
                f"{len(transcriptomics)} transcriptomic experimental "
                "samples were identified in the parsed ImmPort manifest."
                if transcriptomics_true
                else
                "Transcriptomic samples were not identified."
            ),
            [
                source_manifest,
            ],
        ),

        "eif2ak4_measurable": evidence_item(
            eif_value,
            eif_confidence,
            eif_evidence,
            [
                source_manifest,
            ],
        ),

        "quantitative_cd8_response_available": evidence_item(
            "true"
            if cd8_quantitative_true
            else "unknown",
            "high"
            if cd8_quantitative_true
            else "low",
            (
                f"{n_cd8_rows} participant-level quantitative CD8 "
                "response measurements with numeric values were found "
                "in ImmPort lab_test.txt."
                if cd8_quantitative_true
                else
                "No numeric CD8 response measurements were found."
            ),
            [
                source_lab_test,
            ],
        ),

        "appropriate_timepoints": evidence_item(
            "true"
            if appropriate_timepoints_true
            else "unknown",
            "high"
            if appropriate_timepoints_true
            else "low",
            (
                f"Early transcriptomic measurements at days "
                f"{early_days} are linked to later quantitative CD8 "
                f"measurements at days {outcome_days}."
                if appropriate_timepoints_true
                else
                "The required early-predictor/later-outcome timing "
                "relationship was not fully established."
            ),
            [
                source_manifest,
                source_biosample,
                source_lab_test,
            ],
        ),

        "participant_level_linkage": evidence_item(
            "true"
            if participant_linkage_true
            else "unknown",
            "high"
            if participant_linkage_true
            else "low",
            (
                f"All {n_cd8_subjects} subjects with quantitative CD8 "
                f"outcomes also have early transcriptomic measurements; "
                f"overlap={len(overlap_subjects)} subjects."
                if participant_linkage_true
                else
                (
                    "Complete participant-level linkage between early "
                    "transcriptomics and later CD8 outcomes was not established."
                )
            ),
            [
                source_manifest,
                source_biosample,
                source_lab_test,
            ],
        ),

        "predictor_data_accessible": evidence_item(
            "true"
            if predictor_accessible
            else "unknown",
            "high"
            if predictor_accessible
            else "low",
            (
                f"Transcriptomic samples are linked to "
                f"{len(geo_accessions)} GEO GSM accessions."
                if predictor_accessible
                else
                "Accessible transcriptomic predictor data were not verified."
            ),
            [
                source_manifest,
            ],
        ),

        "outcome_data_accessible": evidence_item(
            "true"
            if outcome_accessible_true
            else "unknown",
            "high"
            if outcome_accessible_true
            else "low",
            (
                f"{n_cd8_rows} numeric CD8 outcome values are directly "
                "available in ImmPort lab_test.txt and all map to "
                "participant biosamples."
                if outcome_accessible_true
                else
                "Participant-level numeric CD8 outcomes were not fully accessible."
            ),
            [
                source_lab_test,
                source_biosample,
            ],
        ),
    }

    return {

        "dataset_id": accession,
        "repository": "ImmPort",

        "criteria": criteria,

        "assay_context": {

            "assays_detected": {

                "transcriptomics": {
                    "detected": transcriptomics_true,
                    "matched_terms": sorted(
                        set(
                            transcriptomics[
                                "measurement_technique"
                            ].astype(str)
                        )
                    ),
                },

                "quantitative_cd8_lab_test": {
                    "detected": cd8_quantitative_true,
                    "matched_terms": sorted(
                        set(
                            (
                                cd8_quantitative[
                                    "NAME_PREFERRED"
                                ].astype(str)
                                + " "
                                + cd8_quantitative[
                                    "NAME_REPORTED"
                                ].astype(str)
                            )
                        )
                    ),
                },
            },

            "response_modalities": {
                "cellular_response": cd8_quantitative_true,
                "quantitative_cd8_response": cd8_quantitative_true,
            },

            "timepoints_detected": all_timepoints,
        },

        "data_summary": {

            "manifest_rows": len(
                manifest
            ),

            "transcriptomic_rows": len(
                transcriptomics
            ),

            "early_transcriptomic_subjects": len(
                early_tx_subjects
            ),

            "geo_gsm_accessions": len(
                geo_accessions
            ),

            "quantitative_cd8_rows": n_cd8_rows,

            "quantitative_cd8_subjects": n_cd8_subjects,

            "cd8_subjects_with_early_transcriptomics": len(
                overlap_subjects
            ),

            "all_cd8_subjects_have_early_transcriptomics":
                all_cd8_have_early_tx,

            "early_transcriptomic_days":
                early_days,

            "cd8_outcome_days":
                outcome_days,
        },

        "adapter_notes": [
            (
                "Evidence was derived from the team's parsed "
                "sample_manifest.tsv plus raw ImmPort Tab tables."
            ),
            (
                "Quantitative CD8 outcome accessibility is based on "
                "numeric lab_test.txt records linked through biosample.txt."
            ),
            (
                "EIF2AK4/GCN2 measurability remains unresolved until "
                "the GEO expression platform or matrix is inspected."
            ),
        ],
    }


def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Convert real parsed ImmPort study data into "
            "Hypothesis2Omics scientific-validation evidence."
        )
    )

    parser.add_argument(
        "--manifest",
        required=True,
        type=Path,
        help="Parsed ImmPort sample_manifest.tsv",
    )

    parser.add_argument(
        "--tab-zip",
        required=True,
        type=Path,
        help="Original ImmPort *_Tab.zip archive",
    )

    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Optional normalized evidence JSON output",
    )

    args = parser.parse_args()

    result = build_evidence(
        args.manifest,
        args.tab_zip,
    )

    text = json.dumps(
        result,
        indent=2,
    )

    print(text)

    if args.output:

        args.output.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        args.output.write_text(
            text + "\n",
            encoding="utf-8",
        )


if __name__ == "__main__":
    main()